---
Name: tinify
---

SilverStripe\SiteConfig\SiteConfig:
  extensions:
    - Goldfinch\Tinify\Extensions\SiteConfigExtension

SilverStripe\Assets\Image:
  extensions:
    - Goldfinch\Tinify\Extensions\TinifyImageExtension
