---
Name: goldfinch-tinify
After:
  - '#goldfinch-basement'
---

SilverStripe\SiteConfig\SiteConfig:
  extensions:
    - Goldfinch\Tinify\Extensions\SiteConfigExtension

SilverStripe\Assets\Image:
  extensions:
    - Goldfinch\Tinify\Extensions\TinifyImageExtension
